import { Outfit } from "next/font/google";
import "@/styles/globals.scss";
import Header from "@/components/Header";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <section className="layout">
          <Header />
          <main className="main">{children}</main>
        </section>
      </body>
    </html>
  );
}
